# Generated by Django 3.2.12 on 2022-03-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='Medicine', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Dhaka Medical college', max_length=255),
        ),
    ]
