# Generated by Django 3.2.12 on 2022-02-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pescribedmedicine',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='pescribedmedicine',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='pescribedmedicine',
            name='pescription',
        ),
        migrations.RemoveField(
            model_name='pescription',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='AppointMent',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PescribedMedicine',
        ),
        migrations.DeleteModel(
            name='Pescription',
        ),
    ]
