# Generated by Django 3.2.12 on 2022-04-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0003_appointment_medicine_notification_pescribedmedicine_pescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_no',
            field=models.CharField(default='+880', max_length=100),
        ),
    ]
