# Generated by Django 3.2.12 on 2022-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0004_auto_20220409_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(),
        ),
    ]
