# Generated by Django 3.2.12 on 2022-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0006_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.BooleanField(default=False),
        ),
    ]
