# Generated by Django 3.2.12 on 2022-04-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0007_appointment_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_status',
        ),
    ]
