# Generated by Django 3.2.12 on 2022-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0008_remove_appointment_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pescribedmedicine',
            name='test',
            field=models.ManyToManyField(related_name='tests', to='general_services.MedicalTest'),
        ),
    ]
