# Generated by Django 3.2.12 on 2022-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0009_auto_20220415_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pescribedmedicine',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pescribedmedicine',
            name='follow_up',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Pescription',
        ),
    ]
