# Generated by Django 3.2.12 on 2022-04-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0010_auto_20220415_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pescribedmedicine',
            name='follow_up',
        ),
    ]
