# Generated by Django 3.2.12 on 2022-04-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0011_remove_pescribedmedicine_follow_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pescribedmedicine',
            old_name='pescription',
            new_name='appointment',
        ),
    ]
