# Generated by Django 3.2.12 on 2022-04-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0013_remove_pescribedmedicine_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pescribedmedicine',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_services.appointment'),
        ),
        migrations.AlterField(
            model_name='pescribedmedicine',
            name='medicine',
            field=models.ManyToManyField(null=True, related_name='medicines', to='general_services.Medicine'),
        ),
        migrations.AlterField(
            model_name='pescribedmedicine',
            name='test',
            field=models.ManyToManyField(null=True, related_name='tests', to='general_services.MedicalTest'),
        ),
    ]
