# Generated by Django 3.2.12 on 2022-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_services', '0014_auto_20220415_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pescribedmedicine',
            name='comments',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
